version: '1.0.0'

services:
  backend:
    build: .
    container_name: backend

    ports:
      - 8000:8000
    
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - ./core:/app
    
    environment:
      - DEBUG=True
      - SECRET_KEY=test
    
    depends_on:
      - database
  
  database:
    image : mysql:8 
    container_name : database
    restart : always

    environment :
      - MYSQL_ROOT_PASSWORD=test_password
      - MYSQL_DATABASE=drf_shop_db
    
    ports:
      - "33061:3306"
    
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:

    
