# Generated by Django 6.0.5 on 2026-05-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_imageproduct_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.CharField(blank=True, choices=[('Special', 'Special'), ('Best-Seller', 'Best-Seller')], max_length=11, null=True),
        ),
    ]
