# Generated by Django 6.0.5 on 2026-05-18 14:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_comment_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialSuggestionProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.specialsuggestion')),
            ],
        ),
        migrations.AddField(
            model_name='specialsuggestion',
            name='products',
            field=models.ManyToManyField(related_name='suggestion_products', through='shop.SpecialSuggestionProduct', to='shop.product'),
        ),
    ]
